### ISSUE TITLE
suspicious interaction - some oak has a wasp as habitat

### ISSUE THREAD

**Issue by jhpoelen** [qgroom/Vespa-velutina#2]
See attached screenshot from https://www.globalbioticinteractions.org/?accordingTo=globi%3Aqgroom%2FVespa-velutina&interactionType=ecologicallyRelatedTo 

![Screenshot from 2021-09-13 12-40-49](https://user-images.githubusercontent.com/1084872/133146297-e75167ef-510e-4426-a094-6e87c09c4d68.png)

**Comment by qgroom** [comment]
http://purl.obolibrary.org/obo/RO_0008505 "creates habitat for" replaced with http://purl.obolibrary.org/obo/RO_0002303 "has habitat" for nests in
