### ISSUE TITLE
failed to map interaction type to [http://purl.obolibrary.org/obo/ro_0002574] on line [1]: interaction type unknown to GloBI  at 

### ISSUE THREAD

**Issue by jhpoelen** [qgroom/Vespa-velutina#3]
hey @qgroom - 

It looks like you used a RO term that has not yet been supported by GloBI. Elton complained about it by saying "failed to map interaction type to [http://purl.obolibrary.org/obo/ro_0002574] on line [1]". And, as you hinted, the error message was a bit cryptic because of the raw technical track traces that show the origin of the issue (see stack trace below).

Please let me know if you have any suggestion on how to improve the error logging. 

As I was looking into this issue, I also found that the purl did not resolve for some reason. I've opened a separate issue at: https://github.com/oborel/obo-relations/issues/499 . 

Also, I've added an issue to add support for http://purl.obolibrary.org/obo/ro_0002574 https://github.com/globalbioticinteractions/globalbioticinteractions/issues/703 .
 

from - https://app.travis-ci.com/github/qgroom/Vespa-velutina/jobs/537223933#L226

```
     1 [custom translation mapper not enabled, because the mapper for [local] failed to initialize] Caused by: org.eol.globi.data.StudyImporterException: failed to create interaction type mapper  at org.eol.globi.util.InteractUtil.createInteractionTypeMapperForImporter(InteractUtil.java:48)  at org.eol.globi.process.InteractionListenerImpl.createMappingListener(InteractionListenerImpl.java:48)  at org.eol.globi.process.InteractionListenerImpl.<init>(InteractionListenerImpl.java:35)  at org.eol.globi.data.DatasetImporterWithListener.initListener(DatasetImporterWithListener.java:21)  at org.eol.globi.data.DatasetImporterWithListener.getInteractionListener(DatasetImporterWithListener.java:26)  at org.eol.globi.data.DatasetImporterForTSV.importResource(DatasetImporterForTSV.java:217)  at org.eol.globi.data.DatasetImporterForTSV.importRepository(DatasetImporterForTSV.java:195)  at org.eol.globi.data.DatasetImporterForTSV.importStudy(DatasetImporterForTSV.java:186)  at org.eol.globi.util.DatasetImportUtil.importDataset(DatasetImportUtil.java:65)  at org.globalbioticinteractions.elton.cmd.CmdReview.review(CmdReview.java:154)  at org.globalbioticinteractions.elton.cmd.CmdReview.reviewCachedOrRemote(CmdReview.java:116)  at org.globalbioticinteractions.elton.cmd.CmdReview.run(CmdReview.java:107)  at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:15)  at org.globalbioticinteractions.elton.cmd.CmdLine.run(CmdLine.java:24)  at org.globalbioticinteractions.elton.Elton.main(Elton.java:15) Caused by: org.eol.globi.service.TermLookupServiceConfigurationException: failed to map interaction type to [http://purl.obolibrary.org/obo/ro_0002574] on line [1]: interaction type unknown to GloBI  at org.eol.globi.util.InteractTypeMapperFactoryImpl.buildTypeMap(InteractTypeMapperFactoryImpl.java:122)  at org.eol.globi.util.InteractTypeMapperFactoryImpl.getAndParseTypeMap(InteractTypeMapperFactoryImpl.java:212)  at org.eol.globi.util.InteractTypeMapperFactoryImpl.getTermLookupService(InteractTypeMapperFactoryImpl.java:194)  at org.eol.globi.util.InteractTypeMapperFactoryImpl.mapperForResourceService(InteractTypeMapperFactoryImpl.java:84)  at org.eol.globi.util.InteractTypeMapperFactoryImpl.create(InteractTypeMapperFactoryImpl.java:73)  at org.eol.globi.util.InteractTypeMapperFactoryWithFallback.create(InteractTypeMapperFactoryWithFallback.java:23)  at org.eol.globi.util.InteractUtil.createInteractionTypeMapper(InteractUtil.java:41)  at org.eol.globi.util.InteractUtil.createInteractionTypeMapperForImporter(InteractUtil.java:46)  ... 14 more 
```

**Comment by jhpoelen** [comment]
Please update your term purl to include the correct casing:

```
http://purl.obolibrary.org/obo/RO_0002574
```

instead of 

```
http://purl.obolibrary.org/obo/ro_0002574
```

(see https://github.com/oborel/obo-relations/issues/499)

Turns out that RO IRIs are case sensitive.

**Comment by jhpoelen** [comment]
Please note the Vespa dataset *does* use the correct casing. The underlying issue appears to be something else. Apologies for the confusion.

**Comment by qgroom** [comment]
So is there anything I need to do?

**Comment by jhpoelen** [comment]
@qgroom turns out the issue is on my side. I tried to "cleverly" normalize name  to disambiguate "eat" and "EAT" and "Eat". Unfortunately, I also applied this to identifiers too. And . . . ids are sometimes case sensitive. I opened a separate bug for this at https://github.com/globalbioticinteractions/globalbioticinteractions/issues/704 . 

Thanks for reporting this issue. Your attention to detail uncovered this unfortunately bug. Am working on a fix.

**Comment by jhpoelen** [comment]
(three hours later ... ) Hey @qgroom, I believe I've fixed the issue in the just released Elton v0.12.0 . Please confirm by re-running your travis check, verifying the output and closing this issue. Please holler if issues remain.

Thanks for being patient.

**Comment by qgroom** [comment]
Hi @jhpoelen, I it worked.  🥇 
Sorry for causing such pain. 
Quentin

**Comment by jhpoelen** [comment]
Glad to hear it's working now. Thanks for taking the time to report it! It's these kind of detailed bits that keeps this stuff going. 

Please note that the Zenodo integration now also works a little better, meaning that released versions on Zenodo have right of way over their respective current versions on Github.
